# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('irs_no', models.CharField(default='', max_length=20)),
                ('state_inc', models.CharField(max_length=10, null=True)),
                ('f_year_end', models.CharField(max_length=10, null=True)),
                ('c_type', models.CharField(default='', max_length=30)),
                ('act', models.CharField(max_length=10, null=True)),
                ('file_no', models.CharField(max_length=40, null=True)),
                ('film_no', models.CharField(max_length=40, null=True)),
                ('sic', models.CharField(max_length=150, null=True)),
                ('cik', models.CharField(default='', max_length=30)),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300, null=True)),
                ('doc_name', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=160)),
                ('doc_type', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=30)),
                ('agr_name', models.CharField(max_length=500, null=True)),
                ('agr_type', models.CharField(max_length=500, null=True)),
                ('arg_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_num', models.CharField(default='', max_length=60, unique=True)),
                ('fil_date', models.DateField(null=True)),
                ('fil_date_ch', models.DateField(null=True)),
                ('accepted', models.DateTimeField(null=True)),
                ('doc_count', models.IntegerField(default=1)),
                ('sec_form', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('capacity', models.CharField(max_length=500, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='filing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Filing'),
        ),
        migrations.AddField(
            model_name='company',
            name='filing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Filing'),
        ),
    ]
