# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160320_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filing',
            name='doc_count',
            field=models.IntegerField(default=0),
        ),
    ]
