# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20160320_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='arg_date',
            new_name='agr_date',
        ),
    ]
