# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_document_other_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='sec_form_det',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
